spring:
  profiles:
    active: prod
  datasource:
    password: sistuf_marinha
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9000/postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9009