spring:
  datasource:
    password: ${DATABASE_PASS}
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bdmare.czwli4k1jtfe.us-east-1.rds.amazonaws.com:5432/bd_sistuf
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
server:
  port: 9009
