spring:
  datasource:
    password: 123456
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tests
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 9009