spring:
  datasource:
    password: marinha123!
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sistuf

  jpa:
    format-sql: true
    hibernate:
      ddl-auto: update
  http:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        web: TRACE
