spring:
  datasource:
    password: marinha123!
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sistuf
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 9009